// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO5zjLCTZoAxHoTUlp6l1pjHvIZiPkm5I',
    appId: '1:788959584947:web:f2ded76cf5c0c7890f06c6',
    messagingSenderId: '788959584947',
    projectId: 'online-shop-54b33',
    authDomain: 'online-shop-54b33.firebaseapp.com',
    databaseURL: 'https://online-shop-54b33-default-rtdb.firebaseio.com',
    storageBucket: 'online-shop-54b33.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG3rNoYDU9Jph-UJ12BYpbf1wiwNVAiZ0',
    appId: '1:788959584947:android:a1c4980b601130650f06c6',
    messagingSenderId: '788959584947',
    projectId: 'online-shop-54b33',
    databaseURL: 'https://online-shop-54b33-default-rtdb.firebaseio.com',
    storageBucket: 'online-shop-54b33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDf-wvvtAqZPlq6kVjYcha601XhaS2zFs',
    appId: '1:788959584947:ios:f41a3d9f77a7714c0f06c6',
    messagingSenderId: '788959584947',
    projectId: 'online-shop-54b33',
    databaseURL: 'https://online-shop-54b33-default-rtdb.firebaseio.com',
    storageBucket: 'online-shop-54b33.appspot.com',
    iosBundleId: 'com.example.onlineShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPAGbr1WL311pm33m3dzGZrTSTHLCcwVg',
    appId: '1:188631435903:ios:dd3d3632a5880ef33d0d4a',
    messagingSenderId: '188631435903',
    projectId: 'dars66-7d392',
    storageBucket: 'dars66-7d392.appspot.com',
    iosBundleId: 'com.example.onlineShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjyTe0Gm2jQcSoyU6uTzfr2G392UEm0xA',
    appId: '1:188631435903:web:66a7103cd82943ad3d0d4a',
    messagingSenderId: '188631435903',
    projectId: 'dars66-7d392',
    authDomain: 'dars66-7d392.firebaseapp.com',
    storageBucket: 'dars66-7d392.appspot.com',
    measurementId: 'G-SH6EPCZ7EV',
  );

}