// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjyTe0Gm2jQcSoyU6uTzfr2G392UEm0xA',
    appId: '1:188631435903:web:0ed516f11ae63ab03d0d4a',
    messagingSenderId: '188631435903',
    projectId: 'dars66-7d392',
    authDomain: 'dars66-7d392.firebaseapp.com',
    storageBucket: 'dars66-7d392.appspot.com',
    measurementId: 'G-3J75EG8EGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4WiDZl1qzTE4Z_DUxNu-0xZKXotKUEmY',
    appId: '1:188631435903:android:114e22feb7e1944d3d0d4a',
    messagingSenderId: '188631435903',
    projectId: 'dars66-7d392',
    storageBucket: 'dars66-7d392.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPAGbr1WL311pm33m3dzGZrTSTHLCcwVg',
    appId: '1:188631435903:ios:dd3d3632a5880ef33d0d4a',
    messagingSenderId: '188631435903',
    projectId: 'dars66-7d392',
    storageBucket: 'dars66-7d392.appspot.com',
    iosBundleId: 'com.example.onlineShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPAGbr1WL311pm33m3dzGZrTSTHLCcwVg',
    appId: '1:188631435903:ios:dd3d3632a5880ef33d0d4a',
    messagingSenderId: '188631435903',
    projectId: 'dars66-7d392',
    storageBucket: 'dars66-7d392.appspot.com',
    iosBundleId: 'com.example.onlineShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjyTe0Gm2jQcSoyU6uTzfr2G392UEm0xA',
    appId: '1:188631435903:web:66a7103cd82943ad3d0d4a',
    messagingSenderId: '188631435903',
    projectId: 'dars66-7d392',
    authDomain: 'dars66-7d392.firebaseapp.com',
    storageBucket: 'dars66-7d392.appspot.com',
    measurementId: 'G-SH6EPCZ7EV',
  );

}